config/routes.rb
Rails.application.routes.draw do
  resources :primeminesters
  get 'pm/list'

  get 'pm/idiot'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pradhan.rb
class Pradhan < ApplicationRecord
end

app/models/primeminester.rb
class Primeminester < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pm_controller.rb
class PmController < ApplicationController
  def list
  end

  def idiot
  end
end

app/controllers/primeminesters_controller.rb
class PrimeminestersController < ApplicationController
  before_action :set_primeminester, only: [:show, :edit, :update, :destroy]

  # GET /primeminesters
  # GET /primeminesters.json
  def index
    @primeminesters = Primeminester.all
  end

  # GET /primeminesters/1
  # GET /primeminesters/1.json
  def show
  end

  # GET /primeminesters/new
  def new
    @primeminester = Primeminester.new
  end

  # GET /primeminesters/1/edit
  def edit
  end

  # POST /primeminesters
  # POST /primeminesters.json
  def create
    @primeminester = Primeminester.new(primeminester_params)

    respond_to do |format|
      if @primeminester.save
        format.html { redirect_to @primeminester, notice: 'Primeminester was successfully created.' }
        format.json { render :show, status: :created, location: @primeminester }
      else
        format.html { render :new }
        format.json { render json: @primeminester.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /primeminesters/1
  # PATCH/PUT /primeminesters/1.json
  def update
    respond_to do |format|
      if @primeminester.update(primeminester_params)
        format.html { redirect_to @primeminester, notice: 'Primeminester was successfully updated.' }
        format.json { render :show, status: :ok, location: @primeminester }
      else
        format.html { render :edit }
        format.json { render json: @primeminester.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /primeminesters/1
  # DELETE /primeminesters/1.json
  def destroy
    @primeminester.destroy
    respond_to do |format|
      format.html { redirect_to primeminesters_url, notice: 'Primeminester was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_primeminester
      @primeminester = Primeminester.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def primeminester_params
      params.require(:primeminester).permit(:name, :duriation, :discription)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pm_helper.rb
module PmHelper
end

app/helpers/primeminesters_helper.rb
module PrimeminestersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Govt</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pm/idiot.html.erb
<h1>Pm#idiot</h1>
<p>Find me in app/views/pm/idiot.html.erb</p>

app/views/pm/list.html.erb
<h1>Pm#list</h1>
<p>Find me in app/views/pm/list.html.erb</p>

app/views/primeminesters/_form.html.erb
<%= form_with(model: primeminester, local: true) do |form| %>
  <% if primeminester.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(primeminester.errors.count, "error") %> prohibited this primeminester from being saved:</h2>

      <ul>
      <% primeminester.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :primeminester_name %>
  </div>

  <div class="field">
    <%= form.label :duriation %>
    <%= form.text_field :duriation, id: :primeminester_duriation %>
  </div>

  <div class="field">
    <%= form.label :discription %>
    <%= form.text_area :discription, id: :primeminester_discription %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/primeminesters/edit.html.erb
<h1>Editing Primeminester</h1>

<%= render 'form', primeminester: @primeminester %>

<%= link_to 'Show', @primeminester %> |
<%= link_to 'Back', primeminesters_path %>

app/views/primeminesters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Primeminesters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Duriation</th>
      <th>Discription</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @primeminesters.each do |primeminester| %>
      <tr>
        <td><%= primeminester.name %></td>
        <td><%= primeminester.duriation %></td>
        <td><%= primeminester.discription %></td>
        <td><%= link_to 'Show', primeminester %></td>
        <td><%= link_to 'Edit', edit_primeminester_path(primeminester) %></td>
        <td><%= link_to 'Destroy', primeminester, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Primeminester', new_primeminester_path %>

app/views/primeminesters/new.html.erb
<h1>New Primeminester</h1>

<%= render 'form', primeminester: @primeminester %>

<%= link_to 'Back', primeminesters_path %>

app/views/primeminesters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @primeminester.name %>
</p>

<p>
  <strong>Duriation:</strong>
  <%= @primeminester.duriation %>
</p>

<p>
  <strong>Discription:</strong>
  <%= @primeminester.discription %>
</p>

<%= link_to 'Edit', edit_primeminester_path(@primeminester) %> |
<%= link_to 'Back', primeminesters_path %>